---
title: Headlines
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
url: http://headlinesjournalism.co.uk
description: Lincolnshire-based freelance journalist
permalink: pretty
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
- bower_components
- config.codekit3
- CHANGELOG.md
- LICENSE.md
- bower.json
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
company: Headlines Journalism
email: info@headlinesjournalism.co.uk
google_site_verification: 
analytics: 
logo: "/assets/img/layout/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
social:
  facebook: 
  instagram: 
  twitter: 
  vimeo: 
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
